import os
import sys


def clean_temp_files(root_dir):
    # Common temporary file extensions generated by LaTeX
    temp_extensions = [
        ".aux", ".bbl", ".blg", ".brf", ".idx",
        ".ilg", ".ind", ".lof", ".log", ".lot",
        ".out", ".toc", ".acn", ".acr", ".alg",
        ".glg", ".glo", ".gls", ".ist", ".fls",
        ".fdb_latexmk", ".synctex.gz", ".tdo"
    ]

    deleted = 0
    for dirpath, _, filenames in os.walk(root_dir):
        for filename in filenames:
            if any(filename.endswith(ext) for ext in temp_extensions):
                file_path = os.path.join(dirpath, filename)
                try:
                    os.remove(file_path)
                    print(f"Deleted: {file_path}")
                    deleted += 1
                except Exception as e:
                    print(f"Could not delete {file_path}: {e}")
    print(f"Total temporary files deleted: {deleted}")


def main():
    # If a directory is provided as an argument, use it; else use current directory.
    root_dir = sys.argv[1] if len(sys.argv) > 1 else os.getcwd()
    print(f"Cleaning temporary files in: {root_dir}")
    clean_temp_files(root_dir)


if __name__ == '__main__':
    main()
